ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'

urlpatterns = [
    path('adcart/<int:p>',views.addtocart,name='add'),
    path('viewcart',views.viewcart,name='viewcart'),
    path('remcrt/<int:k>',views.remove_quantity,name='removeqnt'),
    path('remitem/<int:r>',views.remove_item,name='removeitem'),
    path('ordr',views.placeorder,name='order')

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'
urlpatterns = [
    path('srch/',views.search,name='searchproducts')

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'
urlpatterns = [
    path('',views.allcategories,name='allctg'),
    path('allprdt/<int:c>',views.allproducts,name='prdt'),
    path('login/',views.userlogin,name='login'),
    path('reg/',views.register,name='register'),
    path('dtl/<int:p>',views.productdtl,name='details'),
    path('logout',views.user_logout,name='logout'),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User


class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quantity * self.product.price

    def __str__(self):
        return self.product.name


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items = models.IntegerField()
    ordered_date = models.DateField(auto_now=True)
    address = models.TextField()
    phone = models.BigIntegerField()
    delivery_status = models.CharField(max_length=200, default='pending')
    order_status = models.CharField(max_length=200, default='pending')




class Account(models.Model):
    account_no=models.BigIntegerField(default=123456)
    acc_type=models.CharField(max_length=500,default='savings')
    amount=models.IntegerField(default=1000)
    def __str__(self):
        return str(self.account_no)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField()
    images = models.ImageField(upload_to="categories", null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    description = models.TextField()
    images = models.ImageField(upload_to="products", null=True, blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart,Order,Account


# Create your views here.
@login_required
def viewcart(request):
    u = request.user
    c = Cart.objects.filter(user=u)
    total=0
    for i in c:
        total=total+(i.quantity*i.product.price)

    return render(request, 'cart.html', {'c': c,'total':total})


@login_required
def addtocart(request, p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        c = Cart.objects.get(user=u, product=p)
        if p.stock > 0:
            c.quantity += 1
            p.stock -= 1
            p.save()
            c.save()
    except:
        if p.stock > 0:
            c = Cart.objects.create(user=u, product=p, quantity=1)
            p.stock -= 1
            p.save()
            c.save()
    return viewcart(request)


def remove_quantity(request, k):
    p = Product.objects.get(id=k)
    u = request.user
    try:
        c = Cart.objects.get(user=u, product=p)
        if c.quantity > 1:
            c.quantity -= 1
            p.stock += 1
            p.save()
            c.save()
        else:
            c.delete()
            p.stock+=1
            p.save()

    except:
        pass

    return viewcart(request)


def remove_item(request, r):
    p = Product.objects.get(id=r)
    u = request.user
    try:
        c = Cart.objects.get(user=u, product=p)
        p.stock += c.quantity
        print(p.stock)
        p.save()
        c.delete()
    except:
        pass
    return viewcart(request)
def placeorder(request):
    if request.method=="POST":
        a=request.POST['adrs']
        p=request.POST['phn']
        acc=request.POST['acno']
        u = request.user
        c = Cart.objects.filter(user=u)
        print(c)
        total = 0
        for i in c:
            total = total + (i.quantity * i.product.price)
        try:
            acc=Account.objects.get(account_no=acc)
            if(acc.amount>=total):
                acc.amount=acc.amount-total
                acc.save()
                for i in c:
                    od=Order.objects.create(user=u,product=i.product,no_of_items=i.quantity, address=a,phone=p,order_status='paid')
                    od.save()
                    print('success')
                c.delete()
                msg='order placed successfully'
                return render(request,'orderdetails.html',{'msg':msg})
            else:
                msg = 'Insufficient Balance'
                return render(request, 'orderdetails.html', {'msg': msg})
        except:
            pass

    return render(request,'order.html')

ecommerce/search/views.py
from django.shortcuts import render
from django.http import HttpResponse
from shop.models import Product,Category
from django.db.models import Q

# Create your views here.
def search(request):
    if request.method == "POST":
        query = request.POST['srch']
        prdt=Product.objects.filter( Q(name__contains=query) | Q(category__name__contains=query))
        if(prdt):
            cnt=Product.objects.filter(Q(name__contains=query) | Q(category__name__contains=query)).count()
            return render(request, 'search.html', {'query': query,'prdt':prdt,'cnt':cnt})
        else:
            return HttpResponse('no result')

    return render(request, 'search.html',)

ecommerce/shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from shop.models import Category,Product
from django.contrib.auth.decorators import login_required

# Create your views here.
def allcategories(request):
    c = Category.objects.all()
    return render(request, 'category.html', {'c': c})

@login_required
def allproducts(request,c):
    ct = Category.objects.get(id=c)
    p=Product.objects.filter(category=ct)
    return render(request, 'products.html',{"ct":ct,"p":p})
def userlogin(request):
    if (request.method == 'POST'):
        u = request.POST['user']
        p = request.POST['password']
        user = authenticate(username=u, password=p)
        if user:
            login(request,user)
            return render(request,'category.html')
        else:
            return HttpResponse("no registered user")
    return render(request,'login.html')
def register(request):
    if (request.method == 'POST'):
        u = request.POST['username']
        p = request.POST['password']
        eml = request.POST['email']
        fnm = request.POST['fname']
        lnm = request.POST['lname']

        user = User.objects.create_user(username=u, password=p, email=eml, first_name=fnm, last_name=lnm)
        user.save()
    return render(request,'register.html')
@login_required
def productdtl(request,p):
    km = Product.objects.get(id=p)
    return render (request,"details.html",{'km':km})
@login_required
def user_logout(request):
    logout(request)
    return allcategories(request)

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lobster&family=Madimi+One&family=Ruluko&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light col-12  ">
  <a class="navbar-brand  ms-4" href="#"><img src="{% static 'images/carib.png' %}" height="50px" width="110px">
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:allctg' %}">Home </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           All Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
          <a class="dropdown-item" href="{% url 'shop:prdt' i.id %}">{{i.name}}</a>
            {% endfor %}
        </div>
           </li>
          {% if user.is_authenticated %}
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:logout' %}">Logout </a>
      </li>
        {% else %}

        <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:login' %}">Login </a>
      </li>
                <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:register' %}">Register </a>
      </li>
            <li class="nav-item active">
        <h4 class="nav-link text text-primary" >Welcome User</h4>
      </li>


        {% endif %}
    </ul>

  </div>
       <form class="d-flex" method="POST" action="{%  url 'search:searchproducts' %}" style="margin-right:25px">
          {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search products" name="srch" aria-label="Search">
        <button class="btn btn-success" type="submit">Search</button>
      </form>
    {% if user.is_authenticated  %}
     <a href="{% url 'cart:viewcart'%}"><i class="fa-solid fa-cart-shopping" style="margin-right:25px; color:black;">{{cnt}}</i></a>
    {% endif %}
</nav>

{% block content %}
{% endblock %}


</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-sm-7">
            <table class="table table-bordered border-primary">
                <tr>
                    <th colspan="6">Cart Item</th>
                </tr>

                {% for i in c %}
    <tr>
        <td><img src="{{ i.product.images.url }}" alt="" height="100px" width="100px"></td>
        <td><h4 class="text mt-5">{{ i.product.name }}</h4></td>
        <td>
            <p>product-ID:{{ i.product.id }}</p>
            {% if i.product.stock > 0 %}
                <p style="display:inline;">Quantity: <a href="{% url 'cart:add' i.product.id %}"><i class="fa-solid fa-plus" style="border:1px solid; border-radius:30px;"></i></a>
            <h5 style="display:inline;" >{{ i.quantity }}</h5>
            <a href="{% url 'cart:removeqnt' i.product.id %}"><i class="fa-solid fa-minus" style="border:1px solid; border-radius:30px;"></i></a>
            </p>
            {% else %}
               <p style="display:inline;">Quantity:
            <h5 style="display:inline;" >{{ i.quantity }}</h5>
            <a href="{% url 'cart:removeqnt' i.product.id %}"><i class="fa-solid fa-minus" style="border:1px solid; border-radius:30px;"></i></a>
               </p>
            {% endif %}
            <p>unit price:{{ i.product.price }}</p>
        </td>

         <td>
        <p><strong>subtotal: {{i.quantity}}*{{i.product.price}}={{i.subtotal}}</strong></p>
         </td>
        <td>
                  <a href="{% url 'cart:removeitem' i.product.id %}" class="btn btn-primary">Remove</a>

        </td>
    </tr>
                {% endfor %}
            </table>

                </div>
        <div class="col-sm-4">
              <table class="table table-bordered border-primary">
                <tr>
                    <th colspan="4">CheckOut</th>
                </tr>
                  <tr>
                      <td><h4>Total amount is {{total}}</h4></td>
                  </tr>
            </table>
            <a href="{% url 'shop:allctg' %}" class="btn btn-primary">Continue Shopping</a>
            <a href="{% url 'cart:order' %}" class="btn btn-primary" style="position:relative; left">Place Order</a>




              </div>

    </div>
</div>



{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class=" mt-2">
    <img src="{% static 'images/Banner for e commerce website 2.jpg' %}" height="495px" width="100%" >

</div>
<div class=" container-fluid mt-4">
    <h3 style="text-align:center;">Our Collections</h3>
    <p style="text-align:justify; word-spacing: 5px;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
        and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
<div class=" container-fluid mt-4">
    <div class="row ms-5">
        {% for i in c %}
        <div class=" col-xl-4 col-l-6 col-sm-12 mt-3">
             <div class="card" style="width: 25rem; height:595px; ">
            <img src="{{ i.images.url }}" class="card-img-top" style="width:100%; height:283px">
            <div class="card-body ">
          <h5 class="card-title" style="position:relative; left:136.5px;">{{i.name}}</h5>
          <p class="card-text">{{i.description}}</p>
          <a href="{% url 'shop:prdt' i.id %}" class="btn btn-primary"  style="position:relative; ">Products</a>
          </div>
       </div>
                    </div>
        {% endfor %}

    </div>

</div>
{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %} Details{% endblock%}</title>
{% block content %}
<div class="container" style="width:85%">
    <div class="row mt-4" >
        <div class="col-xl-6 col-sm-12" style="position:relative; left:40px;">
    <img src="{{ km.images.url }}" height="350px" width="370px">
</div>
<div class="col-xl-5 col-sm-12" style="position:relative;">
    <h3><strong>{{ km.name }}</strong></h3>
    <p>{{ km.description }}</p>
    <h5>Stock left: {{ km.stock }}</h5>
    <h4>Price: &#8377;{{ km.price }}</h4>
    {% if user.is_superuser == True %}
    {% if km.stock > 0 %}
          <h3 class="text text-danger">Product In Stock</h3>
          <a href="{% url 'admin:index'  %}" class="btn btn-primary">Add Stock</a>
    {% else %}
          <h3 class="text text-danger">out of Stock</h3>
          <a href="{% url 'admin:index'  %}" class="btn btn-primary">Add Stock</a>
    {% endif %}


    {% else %}
    {% if km.stock > 0 %}
        <a href="{% url 'cart:add' km.id %}" class="btn btn-primary">Add To Cart</a>
    {% else %}
        <button class="btn btn-primary disabled" disabled>Add To Cart</button>
          <h3 class="text text-danger">out of Stock</h3>

    {% endif %}
</div>
    </div>
</div>
    {% endif %}
{% endblock %}

ecommerce/templates/exp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
</html>

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
<h1>Registered User Login Here!</h1>
    </center>
<div class="container" style="width:50%">
<form method="POST">
  {% csrf_token %}
    <div class="form-label">
    <label for="name">Username</label>
    <input type="Text" class="form-control" id="name" placeholder="username" name="user">
  </div>
  <div class="form-label">
    <label for="Password1">Password</label>
    <input type="password" class="form-control" id="Password1" placeholder="Password" name="password">
  </div>
  <center>
    <button type="submit" class="btn btn-primary">Submit</button>
    </center>

    </form>
</div>


{% endblock %}

ecommerce/templates/order.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %} order{% endblock%}</title>

{% block content %}
<center><h3>ORDER FORM</h3></center>
<div class="container"  style="width:50%" >
<form method="POST">
  {% csrf_token %}

  <div class="form-label">
    <label for="address"> address</label>
    <input type="text" class="form-control" id="address" name="adrs" aria-describedby="emailHelp" placeholder="Enter address">
  </div>

   <div class="form-label">
    <label for="phoneno">phone no</label>
    <input type="number" class="form-control" id="phoneno" placeholder="enter phone number" name="phn">
  </div>

   <div class="form-label">
    <label for="accno">Account no</label>
    <input type="number" class="form-control" id="accno" placeholder="enter account number" name="acno">
  </div>


<center>
  <button type="submit" class="btn btn-primary">Submit</button>
    </center>
</form>
</div>


{% endblock %}

ecommerce/templates/orderdetails.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>{{msg}}</h2>
{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %} Product List{% endblock%}</title>

{% block content %}
<div class=" mt-2">
    <img src="{{ ct.images.url }}" height="495px" width="100%" >

</div>
<div class=" container-fluid mt-4">
    <h3 style="text-align:center;">{{ct.name}}</h3>
    <p style="text-align:justify; word-spacing: 5px;">{{ct.description}}</p>
</div>
<div class=" container-fluid mt-4">
    <div class="row ms-5">
        {% for i in p %}
        <div class=" col-xl-4 col-sm-6 mt-3">
             <div class="card" style="width: 22.5rem; height:415px">
            <img src="{{ i.images.url }}" class="card-img-top mt-1" style="width:65%; height:279px;position:relative; left:69.5px;">
            <div class="card-body ">
          <h5 class="card-title" style="position:relative;">{{i.name}}</h5>

                <p>&#8377;{{i.price}}<span style="position:relative; left:149.5px;"> <strong>Stock Left:{{i.stock}}</strong></span></p>

          <a href="{% url 'shop:details' i.id %}" class="btn btn-primary"  style="position:relative; ;">Product Details</a>
          </div>
       </div>
                    </div>
        {% endfor %}

    </div>

</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Registration Form {% endblock %}</title>
</head>

<body>

{% block content %}
<center><h3>Registration Form</h3></center>
<div class="container"  style="width:50%" >
<form method="POST">
  {% csrf_token %}
    <div class="form-label">
    <label for="name">Username</label>
    <input type="Text" class="form-control" id="name" placeholder="username" name="username">
  </div>
  <div class="form-label">
    <label for="Password1">Password</label>
    <input type="password" class="form-control" id="Password1" placeholder="Password" name="password">
  </div>

  <div class="form-label">
    <label for="Email1">Email address</label>
    <input type="email" class="form-control" id="Email1" name="email" aria-describedby="emailHelp" placeholder="Enter email">
  </div>
   <div class="form-label">
    <label for="Fname">First name</label>
    <input type="Text" class="form-control" id="Fname" placeholder="firstname" name="fname">
  </div>
   <div class="form-label">
    <label for="lname">last name</label>
    <input type="Text" class="form-control" id="lname" placeholder="lastname" name="lname">
  </div>

   <div class="form-label">
    <label for="phoneno">phone no</label>
    <input type="number" class="form-control" id="phoneno" placeholder="enter phone number" name="phn">
  </div>

<center>
  <button type="submit" class="btn btn-primary">Submit</button>
    </center>
</form>
</div>
{% endblock %}
</body>
</html>

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Search Results For {{query}}({{cnt}})</h1>
<div class=" container-fluid mt-4">
    <div class="row ms-5">
        {% for i in prdt %}
        <div class="col-xl-4 col-sm-6 mt-3">
             <div class="card" style="width: 22.5rem; height:360px">
            <img src="{{ i.images.url }}" class="card-img-top mt-1" style="width:65%; height:219px;position:relative; left:69.5px;">
            <div class="card-body ">
                <h5 class="card-title" style="position:relative;"><strong>{{i.name}}</strong></h5>

                <p>&#8377;{{i.price}}<span style="position:relative; left:149.5px;"> <strong>Stock Left:{{i.stock}}</strong></span></p>

          <a href="{% url 'shop:details' i.id %}" class="btn btn-primary"  style="position:relative; ;">Product Details</a>
          </div>
       </div>
                    </div>
        {% endfor %}

</div>
</div>
{% endblock %}